name: Publish Master to PyPI/TestPyPI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "*.py"

jobs:
  publish-testpypi:
    name: Step 1 - Smoke Test on TestPyPI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/project/calyx_lib
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv python install
      - name: Build
        run: uv build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Step 2 - Release to PyPI
    needs: publish-testpypi
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/calyx_lib
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv python install
      - name: Build
        run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1