name: Publish Dev to TestPyPI

on:
  push:
    branches:
      - dev
    paths:
      - ".github/**"
      - "src/**"
      - "*.py"

jobs:
  publish-testpypi:
    name: Build and Publish to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: testpypi
      url: https://test.pypi.org/project/calyx_lib

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Set up Python
        run: uv python install

      - name: Inject Dev Version
        run: |
          COUNT=$(git rev-list --count HEAD)
          VERSION_FILE=$(find src -name "constants.py" | xargs grep -l "VERSION_PYPI")
          sed -i "s/VERSION_PYPI = \"\([0-9][^\"]*\)\"/VERSION_PYPI = \"\1.dev$COUNT\"/" $VERSION_FILE
          echo "New Version: $(grep "VERSION_PYPI" $VERSION_FILE)"

      - name: Build package
        run: uv build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

